options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "asia-south2-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/todo-app:$COMMIT_SHA"
      - "."

images:
  - "asia-south2-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/todo-app:$COMMIT_SHA"
